export const logos: { [key: string]: string } = {
  '49ers': 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/sf.png',
  Alabama: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
  'Appalachian St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
  Arizona: 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
  'Arizona St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
  Arkansas: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
  'Arkansas St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png',
  Army: 'https://a.espncdn.com/i/teamlogos/ncaa/500/349.png',
  Auburn: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
  'Austin Peay': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2046.png',
  BYU: 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
  'Ball State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png',
  Baylor: 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
  Bears: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/chi.png',
  Bengals: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/cin.png',
  Bills: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/buf.png',
  'Boise St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png',
  'Boston College': 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
  'Bowling Green': 'https://a.espncdn.com/i/teamlogos/ncaa/500/189.png',
  Broncos: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/den.png',
  Browns: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/cle.png',
  Buccaneers: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/tb.png',
  Buffalo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
  'C Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png',
  California: 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png',
  Cardinals: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/ari.png',
  Chargers: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/lac.png',
  'Charleston So': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2127.png',
  Chiefs: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/kc.png',
  Cincinnati: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
  Clemson: 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
  Colorado: 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
  Colts: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/ind.png',
  Commanders: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/wsh.png',
  Cowboys: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/dal.png',
  Delaware: 'https://a.espncdn.com/i/teamlogos/ncaa/500/48.png',
  Dolphins: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/mia.png',
  Duke: 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
  Eagles: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/phi.png',
  'East Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
  FAU: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png',
  Falcons: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/atl.png',
  Florida: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
  'Florida St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
  'GA Southern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/290.png',
  Georgia: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
  'Georgia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
  Giants: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/nyg.png',
  Grambling: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png',
  "Hawai'i": 'https://a.espncdn.com/i/teamlogos/ncaa/500/62.png',
  Houston: 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
  Illinois: 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
  Indiana: 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
  Iowa: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
  'Iowa State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
  Jaguars: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/jax.png',
  Jets: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/nyj.png',
  Kansas: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
  'Kansas St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
  Kentucky: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
  LSU: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
  Lions: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/det.png',
  Louisville: 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
  MTSU: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
  Maryland: 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
  Massachusetts: 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png',
  Memphis: 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
  Mercer: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2382.png',
  Miami: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
  Michigan: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
  'Michigan St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
  Minnesota: 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
  'Mississippi St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
  Missouri: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
  'NC State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
  Navy: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',
  Nebraska: 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
  Nevada: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
  'New Mexico': 'https://a.espncdn.com/i/teamlogos/ncaa/500/167.png',
  Nicholls: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png',
  'North Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
  'North Texas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
  Northwestern: 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
  'Notre Dame': 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
  'Ohio State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
  Oklahoma: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
  'Oklahoma St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
  'Ole Miss': 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
  Oregon: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',
  'Oregon St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png',
  Packers: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/gb.png',
  Panthers: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/car.png',
  Patriots: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/ne.png',
  'Penn State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
  Pitt: 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
  'Portland St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png',
  Purdue: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
  Raiders: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/lv.png',
  Rams: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/lar.png',
  Ravens: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/bal.png',
  Rice: 'https://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
  Rutgers: 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
  'SE Missouri': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png',
  SMU: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
  Saints: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/no.png',
  'San Diego St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
  'San José St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/23.png',
  Seahawks: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/sea.png',
  'South Alabama': 'https://a.espncdn.com/i/teamlogos/ncaa/500/6.png',
  'South Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png',
  'South Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
  'Southern Miss': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png',
  Stanford: 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
  Steelers: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/pit.png',
  Syracuse: 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
  TCU: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
  Tennessee: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
  'Tennessee St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2634.png',
  Texans: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/hou.png',
  Texas: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
  'Texas A\u0026M': 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
  'Texas Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
  Titans: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/ten.png',
  Troy: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
  Tulane: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
  Tulsa: 'https://a.espncdn.com/i/teamlogos/ncaa/500/202.png',
  UAB: 'https://a.espncdn.com/i/teamlogos/ncaa/500/5.png',
  'UC Davis': 'https://a.espncdn.com/i/teamlogos/ncaa/500/302.png',
  UCF: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
  UCLA: 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
  'UL Monroe': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png',
  UNLV: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png',
  USC: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
  'UT Martin': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2630.png',
  UTSA: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png',
  Utah: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
  'Utah State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/328.png',
  Vanderbilt: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
  Vikings: 'https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/min.png',
  Virginia: 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
  'Virginia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
  'W Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png',
  'Wake Forest': 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
  Washington: 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png',
  'Washington St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png',
  'Weber St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png',
  'West Virginia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
  'Western KY': 'https://a.espncdn.com/i/teamlogos/ncaa/500/98.png',
  Wisconsin: 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
  Wyoming: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png',
  'Youngstown St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png',
};
